// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "user"

// User mapped from table <user>
type User struct {
	ID           int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Address      string    `gorm:"column:address;not null" json:"address"`
	Challenge    string    `gorm:"column:challenge;not null" json:"challenge"`
	CreatedAt    time.Time `gorm:"column:created_at;not null;autoCreateTime" json:"created_at"`
	UpdatedAt    time.Time `gorm:"column:updated_at;not null;autoUpdateTime" json:"updated_at"`
	WalletUUID   string    `gorm:"column:wallet_uuid;not null" json:"wallet_uuid"`
	WalletName   string    `gorm:"column:wallet_name;not null" json:"wallet_name"`
	Announcement int16     `gorm:"column:announcement;not null" json:"announcement"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
